spring.application.name: sdm-server

slack:
  channel.id: CC13H63EY
  test.channel.id: CC244EPK4

game:
  regular:
    dayOfWeek: 6
    time: 22-24

---

spring :
  profiles : local
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    driver-class-name : com.mysql.jdbc.Driver
    jdbc-url : jdbc:mysql://fcsdm.vps.phps.kr:3306/fcsdm?useUnicode=yes&characterEncoding=utf8
    username : njw0619
    password : skawodn1
    auto-commit : false
    maximum-pool-size : 10
    pool-name : hikari_service

---

spring :
  profiles : prod
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/fcsdm?useUnicode=yes&characterEncoding=utf8
    username : njw0619
    password : skawodn1
    auto-commit : false
    maximum-pool-size : 10
    pool-name : hikari_service